### ISSUE TITLE
Table component throws border error

### ISSUE THREAD

**Issue by Diederik-SV** [ag-media/react-pdf-table#7]
When using the Table component in our NextJS application, it throws an error:
```
"Invalid border width: undefined"
``` 

This is how we setup the Table in our application:
```typescript
<Table>
    <TableHeader
        style={{
            backgroundColor: '#F6F7F8',
        }}
    >
        {section.fields.map((field, index) => (
            <TableCell
                key={`${index}-${uniqueId()}`}
                style={{
                    paddingHorizontal: 6,
                    paddingVertical: 4,
                    flex: index == 0 ? 0 : 1,
                    flexShrink: index == 0 ? 0 : undefined,
                    minWidth: index == 0 ? 50 : undefined,
                    color: '#7C899F',
                }}
            >
                {field.label}
            </TableCell>
        ))}
    </TableHeader>
    {section.data.map((item, rowIndex) => (
        <TableRow key={rowIndex}>
            {section.fields.map((field, index) => (
                <TableCell
                    key={`${index}-${uniqueId()}`}
                    style={{
                        paddingHorizontal: 6,
                        paddingVertical: 4,
                        flex: index == 0 ? 0 : 1,
                        flexShrink:
                            index == 0 ? 0 : undefined,
                        minWidth:
                            index == 0 ? 50 : undefined,
                    }}
                >
                    <Text>{field.render(item)}</Text>
                </TableCell>
            ))}
        </TableRow>
    ))}
</Table>
``` 

The Table component has this function:
```javascript
const style = useMemo(() => [
        {
            width: '100%',
        },
        ...(Array.isArray(styleProps) ? styleProps : [styleProps]),
        tableStyle.borderStyle === 'solid' ? {
            border: 0,
        } : undefined,
    ].filter(Boolean), [styleProps]);
``` 

That is what causing the @react-pdf/stylesheet package to throw an error.

@react-pdf/stylesheet version 5.2.2 has a function called resolveBorderShorthand, line 159. That functions throws the error. Those versions seem not to be compatible and there is no possibility to overwrite the dependency version.

**Comment by KirP32** [comment]
i have same issue

```
import React from "react";
import { PDFViewer } from "@react-pdf/renderer";
import { Page, Text, View, Document, StyleSheet } from "@react-pdf/renderer";
import { Table, TR, TH, TD } from "@ag-media/react-pdf-table";

export default function Test() {
return (
<>
<PDFViewer style={{ width: "100%", height: "100%" }}>
<Document>
<Table>
<TH>
<TD>Header 1</TD>
<TD>Header 2</TD>
</TH>
<TR>
<TD>Data 1</TD>
<TD>Data 2</TD>
</TR>
</Table>
</Document>
</PDFViewer>
</>
);
}


Issue: Error: Invalid border width: undefined
```

**Comment by Kobilacz** [comment]
I solved this issue by pinning the version of @react-pdf dependencies to specific versions, which are listed below.

"@react-pdf/fns": "3.0.0",
"@react-pdf/font": "3.0.1",
    "@react-pdf/image": "3.0.1",
    "@react-pdf/layout": "4.1.3",
    "@react-pdf/pdfkit": "4.0.0",
    "@react-pdf/png-js": "3.0.0",
    "@react-pdf/primitives": "4.0.0",
    "@react-pdf/reconciler": "1.1.3",
    "@react-pdf/render": "4.0.2",
    "@react-pdf/renderer": "4.1.5",
    "@react-pdf/stylesheet": "5.1.0",
    "@react-pdf/textkit": "5.0.1",
    "@react-pdf/types": "2.7.0"

**Comment by push32** [comment]
@mocanew hi, can you guide us regarding this issue? thank you before

import { Table, TR, TH, TD } from "@ag-media/react-pdf-table";
Could not find a declaration file for module '@ag-media/react-pdf-table'. 'c:/Project/nextjs/management-system/node_modules/@ag-media/react-pdf-table/lib/index.esm.mjs' implicitly has an 'any' type.
  There are types at 'c:/Project/nextjs/management-system/node_modules/@ag-media/react-pdf-table/lib/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@ag-media/react-pdf-table' library may need to update its package.json or typings.

**Comment by Diederik-SV** [comment]
> [@mocanew](https://github.com/mocanew) hi, can you guide us regarding this issue? thank you before
> 
> import { Table, TR, TH, TD } from "@ag-media/react-pdf-table"; Could not find a declaration file for module '@ag-media/react-pdf-table'. 'c:/Project/nextjs/management-system/node_modules/@ag-media/react-pdf-table/lib/index.esm.mjs' implicitly has an 'any' type. There are types at 'c:/Project/nextjs/management-system/node_modules/@ag-media/react-pdf-table/lib/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@ag-media/react-pdf-table' library may need to update its package.json or typings.

@push32 Create a ts-env.d.ts file on root level and declare the module as follows:
```typescript
declare module '@ag-media/react-pdf-table';
```

**Comment by push32** [comment]
> > [@mocanew](https://github.com/mocanew) hi, can you guide us regarding this issue? thank you before
> > import { Table, TR, TH, TD } from "@ag-media/react-pdf-table"; Could not find a declaration file for module '@ag-media/react-pdf-table'. 'c:/Project/nextjs/management-system/node_modules/@ag-media/react-pdf-table/lib/index.esm.mjs' implicitly has an 'any' type. There are types at 'c:/Project/nextjs/management-system/node_modules/@ag-media/react-pdf-table/lib/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@ag-media/react-pdf-table' library may need to update its package.json or typings.
> 
> [@push32](https://github.com/push32) Create a ts-env.d.ts file on root level and declare the module as follows:
> 
> declare module '@ag-media/react-pdf-table';

Thanks, working, but same like other the issue now is "Invalid border width: undefined"

**Comment by Diederik-SV** [comment]
> > > [@mocanew](https://github.com/mocanew) hi, can you guide us regarding this issue? thank you before
> > > import { Table, TR, TH, TD } from "@ag-media/react-pdf-table"; Could not find a declaration file for module '@ag-media/react-pdf-table'. 'c:/Project/nextjs/management-system/node_modules/@ag-media/react-pdf-table/lib/index.esm.mjs' implicitly has an 'any' type. There are types at 'c:/Project/nextjs/management-system/node_modules/@ag-media/react-pdf-table/lib/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@ag-media/react-pdf-table' library may need to update its package.json or typings.
> > 
> > 
> > [@push32](https://github.com/push32) Create a ts-env.d.ts file on root level and declare the module as follows:
> > declare module '@ag-media/react-pdf-table';
> 
> Thanks, working, but same like other the issue now is "Invalid border width: undefined"

A temporary fix is to downgrade the versions of @react-pdf to a specific version like @Kobilacz mentioned. But I hope the code within this package will be fixed.

**Comment by Napam** [comment]
It seems that react-pdf has made breaking changes without increasing their major version. It not only broke this package, but some other stuff that we use as well. I support the quickfix by pinning the react pdf versions as mentioned by @Kobilacz. Here is what worked for us:

```
    "@react-pdf/fns": "3.0.0",
    "@react-pdf/font": "3.0.1",
    "@react-pdf/image": "3.0.1",
    "@react-pdf/layout": "4.2.0",
    "@react-pdf/pdfkit": "4.0.0",
    "@react-pdf/png-js": "3.0.0",
    "@react-pdf/primitives": "4.0.0",
    "@react-pdf/reconciler": "1.1.3",
    "@react-pdf/render": "4.0.2",
    "@react-pdf/renderer": "4.1.6",
    "@react-pdf/stylesheet": "5.2.0",
    "@react-pdf/textkit": "5.0.1",
    "@react-pdf/types": "2.7.0",
```

**Comment by push32** [comment]
> It seems that react-pdf has made breaking changes without increasing their major version. It not only broke this package, but some other stuff that we use as well. I support the quickfix by pinning the react pdf versions as mentioned by [@Kobilacz](https://github.com/Kobilacz). Here is what worked for us:
> 
> ```
>     "@react-pdf/fns": "3.0.0",
>     "@react-pdf/font": "3.0.1",
>     "@react-pdf/image": "3.0.1",
>     "@react-pdf/layout": "4.2.0",
>     "@react-pdf/pdfkit": "4.0.0",
>     "@react-pdf/png-js": "3.0.0",
>     "@react-pdf/primitives": "4.0.0",
>     "@react-pdf/reconciler": "1.1.3",
>     "@react-pdf/render": "4.0.2",
>     "@react-pdf/renderer": "4.1.6",
>     "@react-pdf/stylesheet": "5.2.0",
>     "@react-pdf/textkit": "5.0.1",
>     "@react-pdf/types": "2.7.0",
> ```

thank you

**Comment by ZobairQ** [comment]
@pu

> I solved this issue by pinning the version of [@react-pdf](https://github.com/react-pdf) dependencies to specific versions, which are listed below.
> 
> "@react-pdf/fns": "3.0.0", "@react-pdf/font": "3.0.1", "@react-pdf/image": "3.0.1", "@react-pdf/layout": "4.1.3", "@react-pdf/pdfkit": "4.0.0", "@react-pdf/png-js": "3.0.0", "@react-pdf/primitives": "4.0.0", "@react-pdf/reconciler": "1.1.3", "@react-pdf/render": "4.0.2", "@react-pdf/renderer": "4.1.5", "@react-pdf/stylesheet": "5.1.0", "@react-pdf/textkit": "5.0.1", "@react-pdf/types": "2.7.0"

This now gives me `app-index.js:33 TypeError: Cannot read properties of null (reading 'write')
    at PDFDocument.addContent (pdfkit.browser.js:46504:15)
    at PDFDocument.save (pdfkit.browser.js:9270:17)
    at renderNode (index.js:1908:7)
    at eval (index.js:1963:25)
    at Array.forEach (<anonymous>)
    at render (index.js:1963:9)
    at render (react-pdf.browser.js:309:85)
    at async Object.toBlob (react-pdf.browser.js:328:9)`

**Comment by chiragthummar** [comment]
> "@react-pdf/fns": "3.0.0",
>     "@react-pdf/font": "3.0.1",
>     "@react-pdf/image": "3.0.1",
>     "@react-pdf/layout": "4.2.0",
>     "@react-pdf/pdfkit": "4.0.0",
>     "@react-pdf/png-js": "3.0.0",
>     "@react-pdf/primitives": "4.0.0",
>     "@react-pdf/reconciler": "1.1.3",
>     "@react-pdf/render": "4.0.2",
>     "@react-pdf/renderer": "4.1.6",
>     "@react-pdf/stylesheet": "5.2.0",
>     "@react-pdf/textkit": "5.0.1",
>     "@react-pdf/types": "2.7.0",

This works for me in nextjs

**Comment by Diederik-SV** [comment]
@mocanew is this package still supported?

**Comment by taekungkub** [comment]
not work still "Invalid border width: undefined"

**Comment by juusolain** [comment]
Is there any plans to update the react-pdf dependency and fix this issue @mocanew ?

**Comment by mocanew** [comment]
At the moment, we don't see a need to update react-pdf in our projects, so an update of this package is unlikely in the near future. That said, a well-tested PR is always welcome.
Please note that we consider this package a temporary "hack" until a proper solution is developed and therefore we do not maintain it with the same level of attention as a standard package.

**Comment by mocanew** [comment]
After a quick analysis, I found that the issue was caused by how @react-pdf/stylesheet interprets numeric values. I've just deployed @ag-media/react-pdf-table@2.0.2, which should resolve this. Please note that I've only tested the use cases available in storybook stories.

**Comment by matt-oakes** [comment]
I'm still getting the same error, but from the `TableCell` component. Does that also need to be updated to send different properties for `@react-pdf/stylesheet` to interpret it properly?
